# apiVersion: tekton.dev/v1beta1
# kind: TriggerBinding
# metadata:
#   name: simple-binding

# ---

# apiVersion: tekton.dev/v1beta1
# kind: TriggerTemplate
# metadata:
#   name: trigger-workspace
# spec:
#   resourcetemplates:
#     - apiVersion: v1
#       kind: PersistentVolumeClaim
#       metadata:
#         name: pipelinerun-$(uid)-pvc
#       spec:
#         resources:
#           requests:
#             storage:  1Gi
#         volumeMode: Filesystem
#         accessModes:
#           - ReadWriteOnce
#     - apiVersion: tekton.dev/v1beta1
#       kind: PipelineRun
#       metadata:
#         name: pipelinerun-$(uid)
#       spec:
#         pipelineRef:
#             name: pipeline-workspace
#         workspaces:
#           - name: pipeline-workspace
#             persistentVolumeClaim:
#               claimName: pipelinerun-$(uid)-pvc

# ---

apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding-copy

---

apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-copy
spec:
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: docker-creds
        annotations:
          tekton.dev/docker-0: https://docker.io
      type: kubernetes.io/basic-auth
      stringData:
        username: 1oraldsense9
        password: sacjim-nufdI4-dyxfyq
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: secret-service-account
      secrets:
        - name: docker-creds
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  1Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline-copy-workspace
        workspaces:
          - name: pipeline-copy-workspace
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        name: skopeo-run
      spec:
        serviceAccountName: secret-service-account
        taskRef:
          name: skopeo-copy-task
        workspaces:
        - name: images-url
          configmap: 
            name: image-configmap